repos:
  - repo: local
    hooks:
{% set effective_formatter_tool = cookiecutter.quality_tools.formatter if cookiecutter.quality_tools.formatter in cookiecutter._template_supported_choices.quality_tools.formatter else "" %}
{% set effective_linter_tool = cookiecutter.quality_tools.linter if cookiecutter.quality_tools.linter in cookiecutter._template_supported_choices.quality_tools.linter else "" %}
{% set effective_type_checker = cookiecutter.quality_tools.type_checker if cookiecutter.quality_tools.type_checker in cookiecutter._template_supported_choices.quality_tools.type_checker else "" %}
{% if effective_linter_tool == "ruff" %}
      - id: ruff-check
        name: Ruff lint
        entry: ruff check
        language: system
        types_or:
          - python
          - pyi
{% endif %}
{% if effective_formatter_tool == "ruff" %}
      - id: ruff-format
        name: Ruff format
        entry: ruff format --check
        language: system
        types_or:
          - python
          - pyi
{% endif %}
{% if effective_type_checker == "mypy" %}
      - id: mypy
        name: Mypy
        entry: mypy src
        language: system
        pass_filenames: false
{% endif %}
